name: Ejecutar Pruebas

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Checkout repository

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Set random seed to avoid flakiness
      run: |
        python -c "import random; random.seed(28)"

    - name: Run Behave Tests Spanish
      run: |
        source venv/bin/activate
        behave --tags=@spanish

    - name: Run Behave Tests English
      run: |
        source venv/bin/activate
        behave --tags=@english

    - name: Run Pytest Unit Tests
      run: |
        source venv/bin/activate
        pytest tests